import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell
from typing import Dict, List
from datetime import datetime
import json

class NotebookGenerator:
    """Generate Jupyter notebooks from paper structure and generated code"""
    
    def __init__(self):
        self.nb = new_notebook()
        
    def create_header_cell(self, title: str, authors: List[str] = None) -> None:
        """Create notebook header with paper information"""
        authors_str = ", ".join(authors) if authors else "Unknown Authors"
        
        markdown = f"""# {title}

**Authors:** {authors_str}  
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Tool:** Paper2Notebook (Powered by Gemini 3 Flash Preview & MiniMax M2.5)

---

## 📚 About This Notebook

This notebook was automatically generated from a research paper. It contains:
- Abstract and methodology overview
- Runnable PyTorch implementations
- Experimental code (scaled for CPU)
- Visualizations

⚠️ **Note:** Model dimensions have been reduced for CPU execution. Scale up for production use.

---
"""
        self.nb.cells.append(new_markdown_cell(markdown))
    
    def create_setup_cell(self, dependencies: List[str]) -> None:
        """Create setup cell with dependency installation"""
        
        deps_str = " ".join(dependencies)
        
        code = f"""# Installation (run this cell first)
!pip install -q {deps_str}

# Imports
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from typing import List, Tuple, Optional

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)

# Device configuration
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {{device}}')

# Plotting configuration
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette("husl")
"""
        self.nb.cells.append(new_code_cell(code))
    
    def create_section(
        self,
        section_name: str,
        section_content: str,
        code_data: Dict,
        equations: List[str] = None
    ) -> None:
        """Create a complete section with markdown and code cells"""
        
        # Section header
        header_md = f"## {section_name.title()}\n\n"
        
        # Add section content preview
        content_preview = section_content[:500] + "..." if len(section_content) > 500 else section_content
        header_md += f"{content_preview}\n\n"
        
        # Add equations if present
        if equations:
            header_md += "### Key Equations\n\n"
            for eq in equations[:5]:  # Limit to first 5 equations
                header_md += f"$$\n{eq}\n$$\n\n"
        
        self.nb.cells.append(new_markdown_cell(header_md))
        
        # Add explanation cell
        if code_data.get('explanation'):
            explanation_text = self._extract_explanation(code_data['explanation'])
            if explanation_text:
                self.nb.cells.append(new_markdown_cell(f"### Implementation Notes\n\n{explanation_text}"))
        
        # Add code cells
        code_blocks = code_data.get('code_blocks', [])
        for i, code_block in enumerate(code_blocks):
            self.nb.cells.append(new_code_cell(code_block))
    
    def create_colab_button(self) -> None:
        """Create a cell with Colab opening instructions"""
        
        markdown = """---

## 🚀 Open in Google Colab

Click the button below to open this notebook in Google Colab:

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/YOUR_USERNAME/YOUR_REPO/blob/main/notebook.ipynb)

---
"""
        self.nb.cells.append(new_markdown_cell(markdown))
    
    def create_conclusion_cell(self) -> None:
        """Create conclusion and next steps cell"""
        
        markdown = """---

## 📝 Conclusion

This notebook implemented the key components from the research paper. 

### Next Steps:
1. 🔧 **Scale Up**: Increase model dimensions for better performance
2. 📊 **Full Dataset**: Replace synthetic data with real datasets
3. 🎯 **Hyperparameter Tuning**: Optimize learning rate, batch size, etc.
4. 🚀 **GPU Training**: Move to GPU for faster training
5. 📈 **Advanced Metrics**: Add more evaluation metrics

### References:
- Original Paper: [Add link here]
- PyTorch Documentation: https://pytorch.org/docs/

---

**Generated by Paper2Notebook** | [GitHub](https://github.com/YOUR_USERNAME/Paper2Notebook)
"""
        self.nb.cells.append(new_markdown_cell(markdown))
    
    def _extract_explanation(self, full_text: str) -> str:
        """Extract explanation text (non-code) from generated content"""
        # Remove code blocks
        import re
        text_without_code = re.sub(r'```.*?```', '', full_text, flags=re.DOTALL)
        
        # Clean up and return first few paragraphs
        paragraphs = [p.strip() for p in text_without_code.split('\n\n') if p.strip()]
        return '\n\n'.join(paragraphs[:3])
    
    def generate_from_paper_data(self, paper_data: Dict) -> nbformat.NotebookNode:
        """Generate complete notebook from paper data"""
        
        # Header
        metadata = paper_data.get('metadata', {})
        self.create_header_cell(
            title=metadata.get('title', 'Research Paper Implementation'),
            authors=metadata.get('author', '').split(',') if metadata.get('author') else None
        )
        
        # Colab button
        self.create_colab_button()
        
        # Setup cell
        dependencies = paper_data.get('all_dependencies', [])
        self.create_setup_cell(dependencies)
        
        # Sections
        for section_data in paper_data.get('sections', []):
            section_name = section_data['name']
            section_content = section_data['content']
            code_data = section_data['code']
            
            # Pass equations if available (from original paper structure)
            self.create_section(
                section_name=section_name,
                section_content=section_content,
                code_data=code_data,
                equations=[]  # Can be enhanced to filter equations by section
            )
        
        # Conclusion
        self.create_conclusion_cell()
        
        return self.nb
    
    def save(self, filepath: str) -> str:
        """Save notebook to file"""
        with open(filepath, 'w', encoding='utf-8') as f:
            nbformat.write(self.nb, f)
        return filepath
